[package]
name = "grpc-echo-rs"
version = "0.1.0"
authors = ["gong023 <gon.gong.gone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
