apiVersion: v1
kind: Service
metadata:
  name: grpc-echo-rs-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: grpc-echo-rs
  sessionAffinity: None
  type: NodePort
